# Generated by Django 5.2.8 on 2026-03-16 06:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="To'lov miqdori (so'm)")),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kutilgan miqdor')),
                ('status', models.CharField(choices=[('paid', "To'langan"), ('unpaid', "To'lanmagan"), ('partial', "Qisman to'langan")], default='unpaid', max_length=10, verbose_name='Holat')),
                ('method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "Bank o'tkazma")], default='cash', max_length=20, verbose_name="To'lov usuli")),
                ('month', models.PositiveIntegerField(help_text='1-12', verbose_name='Oy (raqam)')),
                ('year', models.PositiveIntegerField(verbose_name='Yil')),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name="To'langan sana")),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Muddati')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan hodim")),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='courses.group', verbose_name='Guruh')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-year', '-month', '-created_at'],
                'unique_together': {('student', 'group', 'month', 'year')},
            },
        ),
    ]
