# Generated by Django 5.2.8 on 2026-03-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Otasining ismi')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('parent_phone', models.CharField(blank=True, max_length=20, verbose_name='Ota-ona telefoni')),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], default='male', max_length=10, verbose_name='Jins')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='Rasm')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Faol emas'), ('graduated', 'Bitirgan')], default='active', max_length=20, verbose_name='Holat')),
                ('registered_at', models.DateField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan sana")),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': "O'quvchi",
                'verbose_name_plural': "O'quvchilar",
                'ordering': ['-registered_at', 'last_name'],
            },
        ),
    ]
