# Generated by Django 5.2.8 on 2026-03-16 06:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Otasining ismi')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('parent_phone', models.CharField(blank=True, max_length=20, verbose_name='Ota-ona telefoni')),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], default='male', max_length=10, verbose_name='Jins')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='Rasm')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Faol emas'), ('graduated', 'Bitirgan')], default='active', max_length=20, verbose_name='Holat')),
                ('registered_at', models.DateField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan sana")),
                ('telegram_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram ID')),
                ('telegram_notifications', models.BooleanField(default=True, verbose_name='Telegram xabarnomalar')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "O'quvchi",
                'verbose_name_plural': "O'quvchilar",
                'ordering': ['-registered_at', 'last_name'],
            },
        ),
    ]
