# Generated by Django 5.2.8 on 2026-03-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('teacher', "O'qituvchi"), ('student', "O'quvchi"), ('accountant', 'Buxgalter')], default='admin', max_length=20),
        ),
    ]
