# Generated by Django 5.2.8 on 2026-03-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Otasining ismi')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], default='male', max_length=10, verbose_name='Jins')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='Rasm')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Faol emas')], default='active', max_length=20, verbose_name='Holat')),
                ('hired_at', models.DateField(blank=True, null=True, verbose_name='Ishga kirgan sana')),
                ('salary_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Oylik maosh')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
                'ordering': ['-created_at', 'last_name'],
            },
        ),
    ]
