# Generated by Django 5.2.8 on 2026-03-10 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='salary_monthly',
        ),
    ]
