# Generated by Django 5.2.8 on 2026-03-16 06:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/', verbose_name='Kurs rasmi')),
                ('name', models.CharField(max_length=200, verbose_name='Kurs nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('duration_months', models.PositiveIntegerField(default=6, verbose_name='Davomiyligi (oy)')),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Oylik to'lov (so'm)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Guruh nomi')),
                ('salary_type', models.CharField(choices=[('fixed', 'Aniq summa'), ('percentage', 'Foiz')], default='fixed', max_length=20, verbose_name='Maosh turi')),
                ('salary_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Oylik maosh')),
                ('salary_percentage', models.IntegerField(default=0, verbose_name='Foiz (%)')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('days', models.CharField(choices=[('odd', 'Toq kunlar (Du, Ch, Ju)'), ('even', 'Juft kunlar (Se, Pa, Sha)'), ('daily', 'Har kuni'), ('weekend', 'Dam olish kunlari')], default='odd', max_length=20, verbose_name='Dars kunlari')),
                ('start_date', models.DateField(verbose_name='Boshlash sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('max_students', models.PositiveIntegerField(default=15, verbose_name="Max o'quvchi soni")),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Xona')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='courses.course', verbose_name='Kurs')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='teachers.teacher', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Imtihon nomi (masalan: Unit 1 Test)')),
                ('score', models.IntegerField(verbose_name='Ball')),
                ('max_score', models.IntegerField(default=100, verbose_name='Maksimal ball')),
                ('date', models.DateField(verbose_name='Sana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='students.student', verbose_name="O'quvchi")),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.group', verbose_name='Guruh')),
            ],
            options={
                'verbose_name': 'Imtihon',
                'verbose_name_plural': 'Imtihonlar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrolled_at', models.DateField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('left_at', models.DateField(blank=True, null=True, verbose_name='Ketgan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='Chegirma (%)')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student', verbose_name="O'quvchi")),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.group', verbose_name='Guruh')),
            ],
            options={
                'verbose_name': "Ro'yxat",
                'verbose_name_plural': "Ro'yxatlar",
                'ordering': ['-enrolled_at'],
                'unique_together': {('student', 'group')},
            },
        ),
    ]
