# Generated by Django 5.2.8 on 2026-03-02 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kurs nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('duration_months', models.PositiveIntegerField(default=6, verbose_name='Davomiyligi (oy)')),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Oylik to'lov (so'm)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Guruh nomi')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('days', models.CharField(choices=[('odd', 'Toq kunlar (Du, Ch, Ju)'), ('even', 'Juft kunlar (Se, Pa, Sha)'), ('daily', 'Har kuni'), ('weekend', 'Dam olish kunlari')], default='odd', max_length=20, verbose_name='Dars kunlari')),
                ('start_date', models.DateField(verbose_name='Boshlash sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('max_students', models.PositiveIntegerField(default=15, verbose_name="Max o'quvchi soni")),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Xona')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='courses.course', verbose_name='Kurs')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_groups', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('left_at', models.DateField(blank=True, null=True, verbose_name='Ketgan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='Chegirma (%)')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student', verbose_name="O'quvchi")),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.group', verbose_name='Guruh')),
            ],
            options={
                'verbose_name': "Ro'yxat",
                'verbose_name_plural': "Ro'yxatlar",
                'ordering': ['-enrolled_at'],
                'unique_together': {('student', 'group')},
            },
        ),
    ]
