# Generated by Django 5.2.8 on 2026-03-18 04:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Xona nomi')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name="Sig'imi (o'quvchi soni)")),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xona',
                'verbose_name_plural': 'Xonalar',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='group',
            name='room',
        ),
        migrations.AddField(
            model_name='group',
            name='room_old',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Xona (eskicha)'),
        ),
        migrations.AddField(
            model_name='group',
            name='room_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='courses.room', verbose_name='Xona'),
        ),
    ]
