# Generated by Django 5.2.8 on 2026-03-18 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_room_remove_group_room_group_room_old_group_room_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='room_new',
        ),
        migrations.AddField(
            model_name='group',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='courses.room', verbose_name='Xona'),
        ),
    ]
