# Generated by Django 5.2.8 on 2026-03-10 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_group_teacher_to_teacher'),
        ('teachers', '0003_remove_teacher_salary_monthly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/', verbose_name='Kurs rasmi'),
        ),
        migrations.CreateModel(
            name='CourseTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_type', models.CharField(choices=[('fixed', 'Aniq summa'), ('percentage', 'Foiz')], default='fixed', max_length=20, verbose_name='Maosh turi')),
                ('salary_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Oylik maosh')),
                ('salary_percentage', models.IntegerField(default=0, verbose_name='Foiz (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_teachers', to='courses.course', verbose_name='Kurs')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_teachers', to='teachers.teacher', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': "Kurs O'qituvchi",
                'verbose_name_plural': "Kurs O'qituvchilar",
                'ordering': ['-created_at'],
            },
        ),
    ]
