# Generated by Django 5.2.8 on 2026-03-18 16:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_group_room_new_group_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_month', models.PositiveIntegerField(verbose_name='Boshlash oyi (1-12)')),
                ('start_year', models.PositiveIntegerField(verbose_name='Boshlash yili')),
                ('duration_months', models.PositiveIntegerField(verbose_name='Davomiyligi (oylar)')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='courses.enrollment', verbose_name="Ro'yxat")),
            ],
            options={
                'verbose_name': 'Bonus',
                'verbose_name_plural': 'Bonuslar',
                'ordering': ['-created_at'],
            },
        ),
    ]
