# Generated by Django 5.2.8 on 2026-03-18 16:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_bonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.PositiveIntegerField(verbose_name='Tanlangan oy (1-12)')),
                ('year', models.PositiveIntegerField(verbose_name='Tanlangan yil')),
                ('percent', models.PositiveIntegerField(default=100, verbose_name='Chegirma (%)')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='courses.enrollment', verbose_name="Ro'yxat")),
            ],
            options={
                'verbose_name': 'Chegirma',
                'verbose_name_plural': 'Chegirmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Bonus',
        ),
    ]
