# Generated by Django 5.2.8 on 2026-03-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_groupdiscount_delete_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('inactive', 'Faol emas'), ('graduated', 'Bitirgan')], default='active', max_length=20, verbose_name='Holat'),
        ),
    ]
