# Generated by Django 5.2.8 on 2026-03-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_enrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdiscount',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Chegirma summasi'),
        ),
        migrations.AddField(
            model_name='groupdiscount',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Foiz (%)'), ('fixed', "Aniq summa (so'm)")], default='percentage', max_length=20, verbose_name='Chegirma turi'),
        ),
        migrations.AlterField(
            model_name='groupdiscount',
            name='percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Chegirma (%)'),
        ),
    ]
