# Generated by Django 5.2.8 on 2026-03-20 11:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_groupdiscount_amount_groupdiscount_discount_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Qo'shilgan sana"),
        ),
    ]
