# Generated by Django 5.2.8 on 2026-03-19 17:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0, verbose_name='Baho')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='attendance.attendancesession', verbose_name='Sessiya')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_grades', to='students.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Kunlik Baho',
                'verbose_name_plural': 'Kunlik Baholar',
                'unique_together': {('session', 'student')},
            },
        ),
    ]
